/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: user.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "user.pb-c.h"
void   user__init
                     (User         *message)
{
  static const User init_value = USER__INIT;
  *message = init_value;
}
size_t user__get_packed_size
                     (const User *message)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__pack
                     (const User *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__pack_to_buffer
                     (const User *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User *
       user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User *)
     protobuf_c_message_unpack (&user__descriptor,
                                allocator, len, data);
}
void   user__free_unpacked
                     (User *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue user__status__enum_values_by_number[2] =
{
  { "IDLE", "USER__STATUS__IDLE", 1 },
  { "BUSY", "USER__STATUS__BUSY", 2 },
};
static const ProtobufCIntRange user__status__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex user__status__enum_values_by_name[2] =
{
  { "BUSY", 1 },
  { "IDLE", 0 },
};
const ProtobufCEnumDescriptor user__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "User.Status",
  "Status",
  "User__Status",
  "",
  2,
  user__status__enum_values_by_number,
  2,
  user__status__enum_values_by_name,
  1,
  user__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const uint32_t user__version__default_value = 65536u;
static const uint32_t user__magic__default_value = 4218459028u;
static const User__Status user__stat__default_value = USER__STATUS__IDLE;
static const ProtobufCFieldDescriptor user__field_descriptors[6] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User, version),
    NULL,
    &user__version__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "magic",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User, magic),
    NULL,
    &user__magic__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stat",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(User, stat),
    &user__status__descriptor,
    &user__stat__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "email",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(User, email),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__field_indices_by_name[] = {
  5,   /* field[5] = email */
  1,   /* field[1] = magic */
  2,   /* field[2] = name */
  3,   /* field[3] = phone */
  4,   /* field[4] = stat */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "User",
  "User",
  "User",
  "",
  sizeof(User),
  6,
  user__field_descriptors,
  user__field_indices_by_name,
  1,  user__number_ranges,
  (ProtobufCMessageInit) user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
